version: 2

volumes:
  myvolume:

networks:
  front:
    driver: bridge
  back:
    driver: bridge

services:
  voting-app:
    build: ./voting-app/.
    volumes:
      - ./voting-app:/app
    ports:
      - "5000:80"
    networks:
     - front
     - back

  redis:
    image: redis
    ports: ["6379"]
    networks:
      - back

  worker:
    build: ./worker
    networks:
      - back

  db:
    image: postgres:9.4
    volumes:
      - "myvolume:/var/lib/postgresql/data"
    networks:
      - back

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    networks:
      - front
      - back
